name: projectcanhan
description: "A new Flutter project for Tet 2026."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# --- KHỐI 1: NƠI KHAI BÁO THƯ VIỆN ---
dependencies:
  flutter:
    sdk: flutter

  # Các thư viện bổ trợ cho game của Huy
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  audioplayers: ^5.2.1
  flutter_fortune_wheel: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# --- KHỐI 2: CẤU HÌNH FLUTTER (ẢNH, FONT, MATERIAL) ---
flutter:
  uses-material-design: true

  # Khai báo thư mục chứa ảnh và âm thanh cho Reno 5
  assets:
    - assets/images/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
